### ISSUE TITLE
Error not propagated to mqtt.js client

### ISSUE THREAD

**Issue by burritoIand** [aws/aws-iot-device-sdk-js-v2#120]
I'm using [async mqtt.js](https://github.com/mqttjs/async-mqtt) to connect to aws iot, and discovered that when an error occurs with connecting the mqtt client, for example the one below, the client will receive a "close" event without any arguments and thus I cannot catch it and handle it.

I'm not sure if this is the right place to ask but figured I'd start here in case someone has advice on how to catch connection errors?

The picture below is from the AWSIotLogsV2 in cloudwatch, & I'm using a custom iot authorizer that otherwise works fine.

![image](https://user-images.githubusercontent.com/230757/102964090-a265c700-449f-11eb-8a77-d500ebcd302d.png)

**Comment by jmklix** [comment]
If the error is with the mqtt.js then I can't help you, but DUPLICATE_CLIENT_ID is a common error that happens if you are creating multiple clients at the same time with the same id.

Check out the [pubsub](https://github.com/aws/aws-iot-device-sdk-js-v2/blob/ba03f5222378a3b1f9a04f1977998588a09b600e/samples/node/pub_sub/index.ts#L170) for an example of how to set this value.

Are you using this sdk? As stated above if the error is with the interaction of async mqtt.js then you should ask this question there.

**Comment by burritoIand** [comment]
hey @jmklix, ok yeah I wasn't exactly sure where to post since I'm not sure if the actual aws iot error is being sent to the client and should be catchable. e.g. ideally the `close` event would contain some information with it whereas it currently doesn't in this situation.

for the time being I just generate a new client id any time the `close` event is triggered

**Comment by jmklix** [comment]
Sorry, you weren't able to use it as expected. If there is a specific change to this sdk that would help you we are taking feature requests. Just create a [new issue](https://github.com/aws/aws-iot-device-sdk-js-v2/issues/new?assignees=&labels=feature-request%2C+needs-triage&template=---feature-request.md&title=) with as much detail as possible.

**Comment by burritoIand** [comment]
will revisit later, thanks
