### ISSUE TITLE
ETA for documentation?

### ISSUE THREAD

**Issue by cyrusadkisson** [aws/aws-iot-device-sdk-js-v2#18]
While I'm glad to see a rework of aws-iot-device-sdk-js, I'm not sure this repo does anybody any good until we have some documentation on how to use it. Is there a rough estimate of when that might be?

**Comment by KaibaLopez** [comment]
Hi @cyrusadkisson ,
First, thanks for opening this issue. 
But sadly no, we have no ETA for documentation right now... having more issues on this helps me to push for that though...
And actually since you're already here, could I ask, what kind of documentation would you say it's the most impactful/we should focus on? 
- examples
- step by step tutorials
- method descriptions

**Comment by cyrusadkisson** [comment]
- Capabilities, purpose, incl. what's new from the last version
- Installation
- Basic usage

**Comment by cdCarlos** [comment]
> Hi @cyrusadkisson ,
> First, thanks for opening this issue.
> But sadly no, we have no ETA for documentation right now... having more issues on this helps me to push for that though...
> And actually since you're already here, could I ask, what kind of documentation would you say it's the most impactful/we should focus on?
> 
>     * examples
> 
>     * step by step tutorials
> 
>     * method descriptions

* Working examples (really cool if step by step)
* Method descriptions

**Comment by kannieWeesNie** [comment]
can this package be used with a Vue.js app?

i tried but get filesys.existsSync is not a function error when trying to create device

**Comment by justinboswell** [comment]
We have not tried it with Vue.js yet. I would suggest opening a feature request issue for that, along with your repro for why it doesn't work now, and then we can prioritize looking into it.

**Comment by jmattsson** [comment]
I'll have to echo @cyrusadkisson's original comment - claiming GA status but providing no documentation is not okay.

I was trying to figure out whether this SDK provides the same retry logic as v1, but without docs it's an absolute time sink. It'll be faster for me to implement Fleet Provisioning myself on top of v1 than try to figure out how to use this version.

**Comment by justinboswell** [comment]
I'm in the process of importing/publishing our docs now. I'll have something soon.

**Comment by justinboswell** [comment]
CRT docs are published: https://awslabs.github.io/aws-crt-nodejs/
IoT Device SDK docs are next.

**Comment by justinboswell** [comment]
IoT docs are up https://aws.github.io/aws-iot-device-sdk-js-v2/globals.html

These are not top notch, because they mostly link back to the API documentation for the service. The service is in the process of re-doing the docs, look for that soon. Also, any specific feedback is certainly welcome so we can improve what we have.
