### ISSUE TITLE
Browser compatibility is broken

### ISSUE THREAD

**Issue by mama-wk** [aws/aws-iot-device-sdk-js-v2#329]
### Describe the bug

In a browser/electron renderer process application using the latest aws-iot-device-sdk-js-v2, the application can be built but crashes when starting.
We see this problem on all our clients, Intel macOS, Apple Silicon macOS, Windows 10, Ubuntu etc.

### Expected Behavior

Browserish apps continue to work as with earlier versions.

### Current Behavior

When using the browserified components of the sdk v1.9.4, the runtime crashes:
```
 INFO  Launching Electron...
App threw an error during load
Error: Cannot find module '/path/to/project/bin/darwin-x64/aws-crt-nodejs'
```

### Reproduction Steps

```
...
import { mqtt } from 'aws-iot-device-sdk-v2/dist/browser';

const client = new mqtt.MqttClient();
const conn = client.new_connection({});
...
```

### Possible Solution

Please see the comment on the PR: https://github.com/aws/aws-iot-device-sdk-js-v2/pull/311#pullrequestreview-1276810735

### SDK version used

1.9.4

### Environment details (OS name and version, etc.)

Intel macOS 12.6.2, Apple Silicon macOS 13, Windows 10, Ubuntu

**Comment by bretambrose** [comment]
Copying most of the response to the PR comment here as well:

Not necessarily.  For example, I don't have any problems running node's shadow sample in the browser given a credentials sourcing refactor.  The key to that though is that I'm using the package.json-build-steps/webpack/tsconfigs from the browser samples which manage the switch under the scenes during the build process.

The intent of the CRT is to be polymorphic (as close as we can get it) across node and browser.  Unfortunately, it does not live up to that intent in its current form.  Currently, your install target/platform comes from using/not-using webpack, config details to webpack, and potentially tsconfig (not sure) which is not a good (clear, easy, works out-of-the-box) experience.

Clearly, the change broke you, but I think the actual problem is not the change itself, but the deeper problem of making browser/node CRT polymorphism invisible and painless.  

I'm not sure what the right path forward here is yet.  I do suspect that you may be able to get your existing code working with appropriate webpack/tsconfig changes though.

**Comment by mama-wk** [comment]
Thank you for the insight on the issue, although it's not very satisfying since we don't have webpack in all our projects. So it seems we are locked on the v1.9.0 for the time being.

**Comment by jmklix** [comment]
Can you take a look at our improved [browser samples](https://github.com/aws/aws-iot-device-sdk-js-v2/tree/main/samples/browser) and let us know if you are still having any problems while trying to use this sdk?
