### ISSUE TITLE
Connection with PKCS11 not working

### ISSUE THREAD

**Issue by skulljoi** [aws/aws-iot-device-sdk-js-v2#373]
### Describe the bug

Trying to use the sample for pkcs11, but I can not make it work.

`npx ts-node index.ts --endpoint "myid-ats.iot.eu-west-1.amazonaws.com" --cert "pkcs11:token=mytoken;object=myobject;type=cert" --pkcs11_lib /usr/lib/arm-linux-gnueabihf/libtpm2_pkcs11.so.1 --pin 0000 --token_label mytoken --key_label mykey --ca_file /greegrass/rootCA.pem --slot_id 1`

Error: aws-c-common: AWS_ERROR_FILE_INVALID_PATH, Invalid file path.
    at new TlsContext (/home/user/my-mqtt-component/node_modules/aws-crt/dist/native/io.js:324:33)
    at new ClientTlsContext (/home/user/my-mqtt-component/node_modules/aws-crt/dist/native/io.js:356:9)
    at AwsIotMqttConnectionConfigBuilder.build (/home/user/my-mqtt-component/node_modules/aws-crt/dist/native/aws_iot.js:439:35)
    at new AwsPublisher (/home/user/my-mqtt-component/publishers/aws-publisher.js:25:31)
    at new Publisher (/home/user/my-mqtt-component/publisher.js:14:20)
    at new ComplementaryDataPublisher (/home/user/my-mqtt-component/complementary-data-publisher.js:12:3)
    at MqttPublisher.startComponent (/home/user/my-mqtt-component/MqttPublisher.js:21:20)
    at new ConfigurationLoader (/home/user/my-mqtt-component/ConfigurationLoader.js:40:22)
    at Object.<anonymous> (/home/user/my-mqtt-component/index.js:4:1)
    at Module._compile (node:internal/modules/cjs/loader:1218:14) {
  code: 'Invalid file path.'
}

### Expected Behavior

Just to print connected

### Current Behavior

exception, the line number is not correct because I added some console.log to debug the code.

Error: aws-c-common: AWS_ERROR_FILE_INVALID_PATH, Invalid file path.
    at new TlsContext (/home/user/my-mqtt-component/node_modules/aws-crt/dist/native/io.js:324:33)
    at new ClientTlsContext (/home/user/my-mqtt-component/node_modules/aws-crt/dist/native/io.js:356:9)
    at AwsIotMqttConnectionConfigBuilder.build (/home/user/my-mqtt-component/node_modules/aws-crt/dist/native/aws_iot.js:439:35)
    at new AwsPublisher (/home/user/my-mqtt-component/publishers/aws-publisher.js:25:31)
    at new Publisher (/home/user/my-mqtt-component/publisher.js:14:20)
    at new ComplementaryDataPublisher (/home/user/my-mqtt-component/complementary-data-publisher.js:12:3)
    at MqttPublisher.startComponent (/home/user/my-mqtt-component/MqttPublisher.js:21:20)
    at new ConfigurationLoader (/home/user/my-mqtt-component/ConfigurationLoader.js:40:22)
    at Object.<anonymous> (/home/user/my-mqtt-component/index.js:4:1)
    at Module._compile (node:internal/modules/cjs/loader:1218:14) {
  code: 'Invalid file path.'
}

### Reproduction Steps

Download the gitlab sample, install the dependencies and run the code

### SDK version used

"aws-iot-device-sdk-v2": "^1.13.0",

### Environment details (OS name and version, etc.)

armv7l GNU/Linux

**Comment by TwistedTwigleg** [comment]
The issue is the `--cert` argument expects a path to the certificate file for the PKCS11 key you imported into your PKCS11 device. The [sample README](https://github.com/aws/aws-iot-device-sdk-js-v2/blob/main/samples/node/pkcs11_connect/README.md#how-to-run) has an example input showing the needed arguments.

In the command shown, you will need to change it to the following:

~~~
npx ts-node index.ts --endpoint "myid-ats.iot.eu-west-1.amazonaws.com" --cert <replace with path to certificate> --pkcs11_lib /usr/lib/arm-linux-gnueabihf/libtpm2_pkcs11.so.1 --pin 0000 --token_label mytoken --key_label mykey --ca_file /greegrass/rootCA.pem --slot_id 1
~~~

Then it should connect like expected.

**Comment by skulljoi** [comment]
> The issue is the `--cert` argument expects a path to the certificate file for the PKCS11 key you imported into your PKCS11 device. The [sample README](https://github.com/aws/aws-iot-device-sdk-js-v2/blob/main/samples/node/pkcs11_connect/README.md#how-to-run) has an example input showing the needed arguments.
> 
> In the command shown, you will need to change it to the following:
> 
> ```
> npx ts-node index.ts --endpoint "myid-ats.iot.eu-west-1.amazonaws.com" --cert <replace with path to certificate> --pkcs11_lib /usr/lib/arm-linux-gnueabihf/libtpm2_pkcs11.so.1 --pin 0000 --token_label mytoken --key_label mykey --ca_file /greegrass/rootCA.pem --slot_id 1
> ```
> 
> Then it should connect like expected.

this is the path to the certificate: "pkcs11:token=mytoken;object=myobject;type=cert", it is inside TPM also

**Comment by TwistedTwigleg** [comment]
The PKCS11 sample expects a path to the certificate on the drive of the computer, rather than a certificate in the PKCS11 device. At this time, we currently do not have support for pulling the certificate for a mTLS connection from the PKCS11 device with the TLS context options like used in the PKCS11 sample.

Currently there are a couple ways to work around this:
* Pull the certificate out of the PKCS11 device and save it to a file. Then pass this file using the `--cert` argument.
* Pull the certificate data directly from the PKCS11 device but instead of saving it to a file, save it to a variable in your Javascript application. Then pass this variable to the PKCS11 builder using the [cert_file_contents property](https://github.com/awslabs/aws-crt-nodejs/blob/aafdfee042f5de6884a7a0fbe84a7068734cc46b/lib/native/io.ts#LL417C9-L417C27) when constructing the PKCS11 connection
  * Replace [this line in the sample](https://github.com/aws/aws-iot-device-sdk-js-v2/blob/main/samples/node/pkcs11_connect/index.ts#LL67C22-L67C22) with `cert_file_contents` and pass the certificate data to it
  * You could also store the PKCS11 certificate data in an environment variable, and then pull the environment variable data into a Javascript variable. That might be easier to interface with the PKCS11 device, depending on the device in question, than trying to get that data directly from the PKCS11 device in Javascript.

**Comment by skulljoi** [comment]
Ok I will try extract from the tpm and use the cert_file_contents, on monday.
I just followed the idea that it is working for the greengrass itself, that I can use both items with the TPM path.
thanks for the tips

**Comment by skulljoi** [comment]
> The PKCS11 sample expects a path to the certificate on the drive of the computer, rather than a certificate in the PKCS11 device. At this time, we currently do not have support for pulling the certificate for a mTLS connection from the PKCS11 device with the TLS context options like used in the PKCS11 sample.
> 
> Currently there are a couple ways to work around this:
> 
> * Pull the certificate out of the PKCS11 device and save it to a file. Then pass this file using the `--cert` argument.
> * Pull the certificate data directly from the PKCS11 device but instead of saving it to a file, save it to a variable in your Javascript application. Then pass this variable to the PKCS11 builder using the [cert_file_contents property](https://github.com/awslabs/aws-crt-nodejs/blob/aafdfee042f5de6884a7a0fbe84a7068734cc46b/lib/native/io.ts#LL417C9-L417C27) when constructing the PKCS11 connection
>   
>   * Replace [this line in the sample](https://github.com/aws/aws-iot-device-sdk-js-v2/blob/main/samples/node/pkcs11_connect/index.ts#LL67C22-L67C22) with `cert_file_contents` and pass the certificate data to it
>   * You could also store the PKCS11 certificate data in an environment variable, and then pull the environment variable data into a Javascript variable. That might be easier to interface with the PKCS11 device, depending on the device in question, than trying to get that data directly from the PKCS11 device in Javascript.

even extracting the pub cert I still having issues:

`Error: aws-c-io: AWS_IO_TLS_CTX_ERROR, Failed to create tls context
    at new TlsContext (/home/user/my-mqtt-component/node_modules/aws-crt/lib/native/io.ts:435:26)
    at new ClientTlsContext (/home/user/my-mqtt-component/node_modules/aws-crt/lib/native/io.ts:467:9)
    at AwsIotMqttConnectionConfigBuilder.build (/home/user/my-mqtt-component/node_modules/aws-crt/lib/native/aws_iot.ts:493:35)
    at build_connection (/home/user/my-mqtt-component/index.ts:77:34)
    at Object.<anonymous> (/home/user/my-mqtt-component/index.ts:83:24)
    at Generator.next (<anonymous>)
    at /home/user/my-mqtt-component/index.ts:12:71
    at new Promise (<anonymous>)
    at __awaiter (/home/user/my-mqtt-component/index.ts:8:12)
    at Object.main [as handler] (/home/user/my-mqtt-component/index.ts:81:12) {
  code: 'Failed to create tls context'`

**Comment by skulljoi** [comment]
> The PKCS11 sample expects a path to the certificate on the drive of the computer, rather than a certificate in the PKCS11 device. At this time, we currently do not have support for pulling the certificate for a mTLS connection from the PKCS11 device with the TLS context options like used in the PKCS11 sample.
> 
> Currently there are a couple ways to work around this:
> 
> * Pull the certificate out of the PKCS11 device and save it to a file. Then pass this file using the `--cert` argument.
> * Pull the certificate data directly from the PKCS11 device but instead of saving it to a file, save it to a variable in your Javascript application. Then pass this variable to the PKCS11 builder using the [cert_file_contents property](https://github.com/awslabs/aws-crt-nodejs/blob/aafdfee042f5de6884a7a0fbe84a7068734cc46b/lib/native/io.ts#LL417C9-L417C27) when constructing the PKCS11 connection
>   
>   * Replace [this line in the sample](https://github.com/aws/aws-iot-device-sdk-js-v2/blob/main/samples/node/pkcs11_connect/index.ts#LL67C22-L67C22) with `cert_file_contents` and pass the certificate data to it
>   * You could also store the PKCS11 certificate data in an environment variable, and then pull the environment variable data into a Javascript variable. That might be easier to interface with the PKCS11 device, depending on the device in question, than trying to get that data directly from the PKCS11 device in Javascript.

thanks it worked!
