### ISSUE TITLE
Ambiguous function name and params

### ISSUE THREAD

**Issue by timeswind** [aws/aws-iot-device-sdk-js-v2#74]
Both keysAccepted and keysRejected have error in its parameters which draws ambiguous provision logic. What is the purpose of passing error to keysAccepted where its name indicates everything is alright?

https://github.com/aws/aws-iot-device-sdk-js-v2/blob/dd60b21f1db29ec1098e1f471b21047505727720/samples/node/fleet_provisioning/index.ts#L109-L133

**Comment by KaibaLopez** [comment]
Hi @timeswind ,
Yea the naming could be a bit better I guess...Technically, they are 2 different kind of subscriptions and you can find more info [here](https://docs.aws.amazon.com/iot/latest/developerguide/fleet-provision-api.html) under **CreateKeysAndCertificate**.

Basically, you can think of them as de-serialization and server errors. Consider the `keysRejected` function,  both responses are technically _"errors"_, `response` being the server telling you "the CreateKeysAndCertificate was rejected because..." while `error` is more of a " Here is what I failed to de-serialized". So since this de-serialization error can happen on the `KeyAccepted` function too, we need `error` there.

That being said, and I hope that makes sense to you, do you have a suggestion on how to make it less ambiguous?

**Comment by timeswind** [comment]
@KaibaLopez in my opinion, de-serialized error and server response error should both be handled by **keysRejected**

**Comment by timeswind** [comment]
@KaibaLopez For the de-serialized error, did you mean errors from **JSON.parse()**? In that case, I think the code should trust the payload send back from aws service is error free.

**Comment by KaibaLopez** [comment]
Hmmm...
If these functions were creating and validating the keys, I'd agree with your point of accepted means everything ok, but in this instance they are the events the device is subscribing to, and subscription to them can fail regardless of what the actual response from the server was... 

Maybe a better name would be `getKeyAccepted` and `getKeyRejected`, then at least there would be less confusion as to what these functions are about maybe? What do you think?

**Comment by bretambrose** [comment]
Ideally, a service should work perfectly and response should always be valid based on the API contract, but that's not the best assumption when developing an SDK especially since the SDK will often be used while developing and testing the service itself.  To be honest, I don't know of any AWS SDKs that don't perform extensive validation on the responses they get.
