### ISSUE TITLE
IOTShadowClient Named Shadow Support

### ISSUE THREAD

**Issue by jarredkenny** [aws/aws-iot-device-sdk-js-v2#94]
**Is your feature request related to a problem? Please describe.**

`IOTShadowClient` does not currently support named shadows, which has forced me to publish named shadow updates over MQTT and forgo the offline benefits of using the `IOTShadowClient` 

**Describe the solution you'd like**

`IOTShadowClient` should support named shadows and allow for named shadows to be updated even when temporarily offline.

**Comment by graebm** [comment]
The NamedShadow operations have been available since version [v1.2.0](https://github.com/aws/aws-iot-device-sdk-js-v2/releases/tag/v1.2.0) (3mo ago)

Unfortunately, the public API docs weren't updated to include them. I just pushed the updates, [see here](https://aws.github.io/aws-iot-device-sdk-js-v2/classes/aws_iot_device_sdk.iotshadowclient.html)
